# Generated by Django 5.0.1 on 2024-01-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo5', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$1AO5Pf8bnmcWpm7Ve08zbu$YgoZxZIjgm2TSJycfkmKGoWr7ZeC/kSB8LbwVu/V6uE=', max_length=128),
        ),
    ]
