# Generated by Django 5.0.1 on 2024-01-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo5', '0002_member_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='country',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='firstname',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='member',
            name='age',
        ),
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='image',
        ),
        migrations.RemoveField(
            model_name='member',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='password',
        ),
        migrations.RemoveField(
            model_name='member',
            name='salary',
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
