# Generated by Django 5.0.1 on 2024-01-29 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo5', '0003_rename_country_member_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='description',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='type',
            new_name='phone_number',
        ),
    ]
