# Generated by Django 5.0.1 on 2024-01-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo5', '0004_rename_description_member_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
