# Generated by Django 5.0.1 on 2024-02-21 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo5', '0006_alter_member_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='address',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='customer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='phone_number',
            new_name='type',
        ),
    ]
